### ISSUE TITLE
Select specific file

### ISSUE THREAD

**Issue by cahyofendhi** [shagiz/AsyncFilePicker#3]
how to select specific file, example i want just select file pdf, does this lib support like that

**Comment by shagiz** [comment]
yes you can pick any file you want. "Attach file" opens default package manager where you can find your files.

**Comment by cahyofendhi** [comment]
hello mr. @shagiz , i mean select .pdf file, when click "Attach file", just display .pdf file

**Comment by shagiz** [comment]
@cahyofendhi I understand, you mean filter by .pdf type. No this function is not available, but I think you can implement this by inheriting FilePickerDialog class and set custom clickListener on file_picker_files view.

your click listener should call method like default one.

```
private fun onFilesOpenClick() {
        val intent = Intent(Intent.ACTION_GET_CONTENT)
        intent.addCategory(Intent.CATEGORY_OPENABLE)

        if (multipleSelect && Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
            intent.putExtra(Intent.EXTRA_ALLOW_MULTIPLE, true)
        }

        intent.type = "*/*" <--- here you can pass type you need "application/pdf" for your case
        startActivityForResult(intent, IntentResolver.REQUESTER)
}
```

**Comment by cahyofendhi** [comment]
oh i see, thanks alot @shagiz
